[API]
# Acesse https://my.telegram.org/auth
ID = 123456 # ID Telegram
HASH = "API Hash Telegram"
BOT_TOKEN = "Token do Bot criado via BotFather"

[ADMIN]
IDS = [2222222222] # IDs dos chats admin

[COMPANY]
NAME = "DriveMatch"
